### ISSUE TITLE
Failing while doing catkin_ make

### ISSUE THREAD

**Issue by PranshuTople** [lprobsth/gazebo_ros_tracked_vehicle_interface#1] opened 2022-04-18 16:45 UTC
I am getting the following error while doing catkin_make after adding your package. 

<a href="https://ibb.co/1vjkNzT"><img src="https://i.ibb.co/GxNqDHR/Screenshot-2022-04-18-at-10-09-24-PM.png" alt="Screenshot-2022-04-18-at-10-09-24-PM" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'></a>
Can you please be more precise on how to use it and make detailed documentation? Or else help me set it up through a video call, and I could help you document it in a better way for others to use.

**Comment by lprobsth** [comment] 2022-04-20 22:01
Sorry for the late answer.

I investigated the problem and besides some minor include problems that are now resolved in the master branch your particular problem is caused by the gazebo9 version shipped with the ROS melodic package list. This version does not include the Twist message type (and as it seems also to not include the SimpleTrackedVehicleInterface plugin).

You need to add the OSRF apt package list with the updated gazebo binary packages. The tutorial is currently offline - but you can follow this tutorial instead for adding the package list:
http://gazebosim.org/tutorials?tut=install_from_source&cat=install#ROSUsers

Afterwards you should be able to update gazebo9 or you can also install gazebo11.

I will update the plugin these days with an in-depth explanation and a catkin environment hook for exporting the GAZEBO_PLUGIN_PATH so gazebo knows the location of the binary plugin file after source the workspace.

**Comment by lprobsth** [comment] 2022-04-21 16:17
I've updated the installation instructions.

The environment hook is not ready yet. But I've added a manual fix in the troubleshooting section for exporting the GAZEBO_PLUGIN_PATH environment variable.

**Closed as completed** 2022-05-11 04:20 UTC
Labels: bug
